### ISSUE TITLE
Overload constructor for alternate-sized die

### ISSUE THREAD

**Issue by kbuffardi** [ChicoState/GameDie#43]
Create an overloaded constructor `GameDie::GameDie(unsigned int)` so that die can be created with any positive number of faces.

If the parameter passed is zero, default to six faced die.

Otherwise, allow a die that has as many faces as provided as a parameter.

**Comment by kbuffardi** [comment]
If the default constructor is used instead, the object should default to a six faced die.

**Comment by shubhamlatkar** [comment]
## Implemented custom constructor for multi face die #43
